apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxygen-deployment
  namespace: grp02eq12-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: oxygen-container
        image: suplavan/oxygencs-grp02-eq12:latest
        ports:
        - containerPort: 8083
        resources:
          requests:
            cpu: "500m"  # 0.5 CPU core
            memory: "128Mi"  # 128 MB
          limits:
            cpu: "1000m"  # 1 CPU core
            memory: "256Mi"  # 256 MB
        envFrom:
        - configMapRef:
            name: my-app-config
        env:
        - name: HOST_TOKEN
          valueFrom:
            secretKeyRef:
              name: my-app-secret
              key: HOST_TOKEN
