apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxygen-deployment
  namespace: grp02eq12-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: oxygen-container
        image: suplavan/oxygencs-grp02-eq12:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
        resources:
          requests:
            cpu: "30m"  # 0.04 CPU core
            memory: "64Mi"  # 54 MB
          limits:
            cpu: "50m"  # 0.05 CPU core
            memory: "128Mi"  # 128 MB
        envFrom:
        - configMapRef:
            name: my-app-config
        env:
        - name: HOST_TOKEN
          valueFrom:
            secretKeyRef:
              name: my-app-secret
              key: HOST_TOKEN
