name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev
        pipenv install --dev black

    - name: Run tests
      run: |
        pipenv run python -m unittest test.test

    - name: Run black
      run: |
        pipenv run black src/ test/

  build_docker:
    runs-on: ubuntu-latest
    needs: test  # Ensure that the 'build' job has completed successfully before running this job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t suplavan/oxygencs-grp02-eq12:latest -t suplavan/oxygencs-grp02-eq12:${{ github.run_number }} .

    - name: Login to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push suplavan/oxygencs-grp02-eq12:latest
        docker push suplavan/oxygencs-grp02-eq12:${{ github.run_number }}

  deploy_to_k8s:
    runs-on: ubuntu-latest
    needs: build_docker

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Kubeconfig
      env:
        KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
      run: |
        mkdir -p $HOME/.kube
        echo "$KUBECONFIG_DATA" | base64 -d > $HOME/.kube/config
        kubectl config set-context --current --namespace=grp02eq12-namespace

    - name: Update Image in k8s deployment YAML
      run: |
        sed -i 's|suplavan/oxygencs-grp02-eq12:latest|suplavan/oxygencs-grp02-eq12:${{ github.run_number }}|' ./src/k8s/deployment/deployment.yaml

    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ./k8s/deployment/oxygen-deployment.yaml

    - name: Check rollout status
      run: |
        kubectl rollout status deployment/oxygen-deployment




